name: CI_Unittest

on:
  push:
    branches:
      - main
      - develop
      - feature/AR-create_tests
  pull_request:
    branches:
      - main
      - develop
      - feature/AR-create_tests

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run unittests
        run: |
          python -m unittest discover -s src/tests -p "*.py"
          
      - name: Upload test artifacts
        uses: actions/upload-artifact@v3 
        with:
          name: test_report
          path: artifacts/
